handleError = (err, res) ->
  res.status(500)
  res.send(err)

export handleError
